#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/bradmairs/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/bradmairs/Documents/sirisos-worktrees/next-slice/apps/mobile"
export "FLUTTER_FRAMEWORK_SWIFT_PACKAGE_PATH=/Users/bradmairs/Documents/sirisos-worktrees/next-slice/apps/mobile/ios/Flutter/ephemeral/Packages/.packages/FlutterFramework"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/bradmairs/Documents/sirisos-worktrees/next-slice/apps/mobile/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=0.2.0"
export "FLUTTER_BUILD_NUMBER=2"
export "DART_DEFINES=U0lSSVNPU19BUElfVVJMPWh0dHA6Ly8xMjcuMC4wLjE6ODAwMA==,RkxVVFRFUl9WRVJTSU9OPTMuNDQuOQ==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049NmIxODJkMmM3NQ==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049NWEyYTZhNDJjYw==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMi4y"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/bradmairs/Documents/sirisos-worktrees/next-slice/apps/mobile/.dart_tool/package_config.json"
